### PR TITLE
Improve Speed of Getting Printer State

### PR DESCRIPTION
**Pull request by YasuhiroFuruta**
Improve speed of Device.GetDeviceDetails().
* Reduced unnecessary page switches.
* Changed the explicit wait timeout of ChromeDriver.Find\*() to 10 seconds **after last action to Chrome**.

### CODE REVIEW

**Comment by kdlucas** [comment]
I like reducing the time to get printer states. Could you explain at a high level how this code works in reducing the time it takes? It it mainly just getting rid of much of the wait time?

**Comment by YasuhiroFuruta** [comment]
I fixed editing mistake on the dead code and added a more improvement.

**Comment by YasuhiroFuruta** [comment]
In result, this PR reduces wait time of finding element to about 40 seconds from about 160 seconds per each 'Device.GetDeviceDetails()' call.

Detail description follows:

To reduce unnecessary page switches:
* Added 'ChromeDriver.page_id' to remember which page is currently displayed.
 * It is reset by 'ChromeDriver.ActionPerformed()' when any action is performed on Chrome.
* Applied following changes to 'CloudPrintMgr.SelectPrinter()' and 'CloudPrintMgr.'.
 * Skip the operation if 'ChromeDriver.page_id' is matched.
 * Set 'ChromeDriver.page_id' if the operation is succeed.
* Reordered the order of getting state on 'Device.GetDeviceDetails()' to following order, to reduce the page switch requirement.
 * From the printer list page. ('GetPrinterErrorState()' and 'GetPrinterWarningState()')
 * From the printer details page. ('GetPrinterState()' and 'GetPrinterStateMessages()')
 * From the printer details page with the advanced details. ('GetPrinterDetails()')
* Added retrying code to 'Device.GetDeviceDetails()' instead of the 'Retry' annotations of 'GetPrinterErrorState()', 'GetPrinterWarningState()', 'GetPrinterState()', 'GetPrinterStateMessages()' and 'GetPrinterDetails()' to reduce the page switch requirement.
* Added reloading page by jump to 'about:blank' before jump to the management page on 'CloudPrintMgr.SelectPrinter()' to keep effectivity of retrying.
 * Removed checking that the printer is already selected, because reloading page resets the selection.

To reduce wait time for finding element:
* Added 'ChromeDriver.last_action_time' to record the time of the last action to Chrome.
 * It is updated by 'ChromeDriver.ActionPerformed()'.
* Added 'ChromeDriver.GetWait()' instead of 'ChromeDriver.wait'.
 * This function returns WebDriver object which waits up to 10 seconds after the last action to Chrome.
 * It reduces total wait time of finding element to less than 10 seconds **per each action to Chrome**.
 * Before this change, the wait time was up to 10 seconds **for each finding element**.

Common changes:
* Added 'ChromeDriver.Get()' to catch all action to Chrome by 'ChromeDriver'.
 * Replaced all 'webdriver.get()' to 'ChromeDriver.Get()'.
* Added 'ChromeDriver.ActionPerformed()' to add codes to handle the actions to Chrome.
 * Added 'ActionPerformed()' call to '\_\_init\_\_()', 'ClickElement()', 'ExecScript()', 'Get()', 'MouseOver()' and 'SendKeys()'.

**Comment by kdlucas** [comment]
Looks good and thanks for the detailed explanation.

**Pull request merged**
