### PR TITLE
Fixed printer state verifying behavior.

### PR DESCRIPTION
**Pull request by YasuhiroFuruta**
- Fixed error accessing non existent "caption" field at testNoMediaInTray().
- Fixed incorrectly finding keyword in UI state message.
- Changed to check all UI messages related to the category.
- ~~Changed to continue running the test until clearing the error state even if the test failed. It prevents effect to other tests.~~

### CODE REVIEW

**Comment by lrbom** [comment]
Hi,

I really like some of the changes you made, especially checking error messages by 'category' in VerifyUiStateMessages().

Some general concerns I have:
1) The current function does not check for NO error messages in the printer, it only checks that there are no error messages in a specific category. I think it'd be much safer to check that there are no errors across all categories.

2) I prefer to raise an exception in the middle of test functions with multiple test cases because the results from the later test depend on the state created by the previous tests. Letting the tests run through might provide false-positives that are hard to track down by the tester even though you are asserting success. 

Please let me know what you think. 
Once again, thanks for your contribution! :)

**Comment by YasuhiroFuruta** [comment]
> 1. The current function does not check for NO error messages in the printer, it only checks that there are no error messages in a specific category. I think it'd be much safer to check that there are no errors across all categories.

Current code already checks that there are no errors across all categories no error message by `self.assertFalse(_device.error_state)` after error cleared.
`_device.error_state`: num_issues(error/warning message count) != 0

> 2. I prefer to raise an exception in the middle of test functions with multiple test cases because the results from the later test depend on the state created by the previous tests. Letting the tests run through might provide false-positives that are hard to track down by the tester even though you are asserting success.

OK, I will change the code to raise an exception in the middle of test if test failed.

> > ~~- Changed to continue running the test until clearing the error state even if the test failed. It prevents effect to other tests.~~

**Comment by YasuhiroFuruta** [comment]
> OK, I will change the code to raise an exception in the middle of test if test failed.

Done.
I tested that changed tests works fine.

**Comment by lrbom** [comment]
Looks good to me, I will merge this now. Thanks again!

**Comment by lrbom** [comment]
Hi,

This commit actually affected other printers so I am reverting this for now. 
The 'Captions' field is actually used to disambiguate between multiple errors to get the most relevant error. Checking for the content and existence of this field will still be useful for many printers. 

Please let me know if this prevents you from passing your tests.

My apologies.

Kevin

**Pull request merged**
